#!/usr/bin/env bash

echo "Optimizing svg figures..."

set -e

find . -type f -path '*/figures/*.svg' -print0 |
while IFS= read -r -d '' file; do
    echo "Processing $file"

    inkscape \
      --export-plain-svg \
      --export-area-drawing \
      --actions="select-all;object-to-path" \
      "$file" -o "$file"

    tmp=$(mktemp)

    if scour --quiet \
      --strip-xml-prolog \
      --enable-id-stripping \
      --enable-comment-stripping \
      --shorten-ids-prefix=PREFIX \
      -i "$file" -o "$tmp"; then
        mv "$tmp" "$file"
    else
        rm -f "$tmp"
        exit 1
    fi
done
