const local_macros = {
  "\\Lagr": "\\mathscr{L}",
  "\\x": "\\cancel{#1}",
  "\\E": "\\vec{E}",
  "\\B": "\\vec{B}",
  "\\A": "\\vec{A}",
  "\\dx": "\\dot{x}",
  "\\dy": "\\dot{y}",
  "\\dz": "\\dot{z}",
  "\\dr": "\\dot{\\r}",
  "\\dq": "\\dot{q}",
  "\\du": "\\dot{u}",
  "\\r": "\\vec{r}",
  "\\v": "\\vec{v}",
  "\\g": "\\vec{g}",
  "\\0": "\\vec{0}",
  "\\ur": "\\vec{u_r}",
  "\\large": ">\\!\\!>",
  "\\small": "<\\!\\!<",
  "\\u": "\\;\\mathrm{#1}",
  "\\lxyz": "\\left(#1,#2,#3\\right)",
  "\\dxyz": "\\mtx{#1 \\\\ #2 \\\\ #3}",
  "\\lxy": "\\left(#1,#2\\right)",
  "\\dxy": "\\mtx{#1 \\\\ #2}",
  "\\eforall": "\\enspace\\forall",
};
