const local_macros = {
  "\\E": "\\vec{E}",
  "\\B": "\\vec{B}",
  "\\A": "\\vec{A}",
  "\\j": "\\vec j",
  "\\k": "\\vec k",
  "\\p": "\\vec p",
  "\\poynting": "\\vec{\\Pi}",
  "\\g": "\\vec g",
  "\\r": "\\vec r",
  "\\v": "\\vec v",
  "\\0": "\\vec 0",
  "\\x": "\\vec x",
  "\\y": "\\vec y",
  "\\z": "\\vec z",
  "\\S": "\\vec S",

  "\\rot": "\\operatorname{\\overrightarrow{rot}}",
  "\\grad": "\\operatorname{\\overrightarrow{grad}}",
  "\\div": "\\operatorname{div}",
  "\\Vol": "\\mathscr{V}",
  "\\Surf": "\\mathscr{S}",
  "\\Contour": "\\mathscr{C}",
  "\\lapl": "\\Delta",
  "\\ur": "\\vec{u}_r",
  "\\uth": "\\vec{u}_{\\theta}",
  "\\uph": "\\vec{u}_{\\varphi}",
  "\\ux": "\\vec{u}_x",
  "\\uy": "\\vec{u}_z",
  "\\uz": "\\vec{u}_z",
  "\\large": ">\\!\\!>",
  "\\small": "<\\!\\!<",
  "\\u": "\\;\\mathrm{#1}",
};
