const local_macros = {
  "\\p": "\\vec{p}",
  "\\E": "\\vec{E}",
  "\\B": "\\vec{B}",
  "\\Lagr": "\\mathscr{L}",
  "\\Proba": "\\mathbf{P}",
  "\\Puiss": "\\mathscr{P}",
  "\\moy": "\\Braket{#1}",
  "\\cte": "\\mathrm{c^{te}}",

  "\\r": "\\vec{r}",
  "\\v": "\\vec{v}",
  "\\g": "\\vec{g}",
  "\\0": "\\vec{0}",
  "\\rot": "\\vec\\nabla\\land",
  "\\div": "\\vec\\nabla\\cdot",
  "\\grad": "\\vec\\nabla",
  "\\lapl": "\\Delta",
  "\\ur": "\\vec{u_r}",
  "\\large": ">\\!\\!>",
  "\\small": "<\\!\\!<",
  "\\u": "\\;\\mathrm{#1}",
  "\\lxyz": "\\mtx{#1, & #2, & #3}",
  "\\dxyz": "\\mtx{#1 \\\\ #2 \\\\ #3}",
  "\\eforall": "\\;\\forall",
};
