name: Generate and deploy github pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          path: source

      - name: Download markup
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download current \
            --repo 3fxcf9/markup \
            --pattern markup-linux-x86_64 \
            --output markup

          chmod +x markup

      - name: Generate site
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          mkdir output
          ./markup ./source ./output --http_root="$REPO_NAME"

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./output

  deploy:
    needs: build-and-deploy

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
