name: Generate and deploy github pages
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          path: source

      - name: Checkout markup
        uses: actions/checkout@v6
        with:
          repository: 3fxcf9/markup
          path: markup

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
          dune-cache: true

      - name: Install markup dependencies
        run: opam install ./markup --deps-only -y

      - name: Build markup
        run: opam exec -- dune build --root markup --profile release

      - name: Generate site
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          mkdir output
          ./markup/_build/default/main/main.exe ./source ./output --http_root="$REPO_NAME"

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./output

  deploy:
    needs: build-and-deploy
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
